### PR TITLE
Regenerate grub.cfg in case grub2 files have changed

### PR DESCRIPTION
**Pull request by william-gr**
DEPENDS: https://github.com/freenas/freenas/tree/issues/25010 
DEPENDS: https://github.com/freenas/ports/tree/issues/25010

Ticket:	#25010

### CODE REVIEW

**Comment by william-gr** [comment]
Jenkins: retest this please

**Comment by kmoore134** [comment]
Jenkins: retest this please

**Comment by kmoore134** [comment]
Jenkins: retest this please

**Comment by kmoore134** [comment]
Jenkins: retest this please

**Pull request closed without merging**
