### PR TITLE
Fix busted link to the more detailed setup guide

### PR DESCRIPTION
**Pull request by justinclift**

### CODE REVIEW

**Comment by justinclift** [comment]
Or optionally cherry pick the patch from here: https://github.com/freenas/corral-build/pull/49 :wink:

**Comment by kmoore134** [comment]
Thanks! We will want to move that wiki entry over to the "build" repo in the near future, but for now at least the link works :)

**Comment by justinclift** [comment]
No worries at all.  I just tried clicking the link and noticed it didn't work.

As an alternative thought, I was thinking maybe migrating the content to the main FN wiki:

  &nbsp; &nbsp; https://wiki.freenas.org/index.php/Main_Page

There's already a "Development" heading, and it probably wouldn't hurt to have all of the wiki stuff in one place.

If that's a decent idea (?), I can probably get around to it either next week or next weekend.

**Comment by kmoore134** [comment]
Oh, that's a much better idea, and I like having it there, instead of trying to keep track of sometimes shifting github repos. Go ahead and send a pull request once you've moved it over.

Thanks Justin, appreciate all the work!

**Comment by justinclift** [comment]
No worries at all. :smile:

**Comment by justinclift** [comment]
Btw, would you be ok to merge this PR too?  https://github.com/freenas/corral-build/pull/49

That fixes the same problem, but in the corral-build repo.

**Pull request merged**
