### PR TITLE
Add support to install FreeNAS onto eMMC storage

### PR DESCRIPTION
**Pull request by sfu420**
Add support to install FreeNAS to onboard eMMC flash storage.
Nowadays more and more device using eMMC storage for the OS.
eMMC is a family of NAND flash memories with control functionality such as ECC, wear leveling and bad-block management.
Successfully tested and installed with ease. Now my system is much faster as it with my USB pen drive was.

### CODE REVIEW

**Comment by amotin** [comment]
And lets start this from ticket.

**Comment by sfu420** [comment]
Yes, it is just a mistake. I wanted to send you only the last 2. I'm sorry.

**Comment by amotin** [comment]
I am curios: what hardware do you have with eMMC?  I can't recall much outside of maybe some Intel NUCs.

**Comment by sfu420** [comment]
I'm using a QNAP TBS-453A with 8GB RAM and Intel Braswell inside. (I've had enough of the bugs of the QNAP OS)
But yes Intel NUC has also eMMC inside. Or it comes out day by day more single board computer with x86 CPU and with some SATA ports, just like the Odoo X86 Ultra or the UP2-Board.

Should I make a ticket as a feature request with all the information of my research regarding the eMMC kernel module?

**Comment by amotin** [comment]
Yes, please create a feature request ticket.

**Comment by sfu420** [comment]
Ticket created with #39123

**Pull request closed without merging**
